- hosts: jboss_eap_fedora_hosts
  remote_user: "{{ ansible_fedora_user }}"
  become: true
  become_user: root
  gather_facts: true

  pre_tasks:
  - name: Install dnf-python
    raw: dnf install python-dnf -y 
  - name: Install libselinux-python
    raw: dnf install libselinux-python -y 

  roles:
  - jboss_common
  - jboss_eap
